PX4/NuttX branch test: master
NuttX:
 - https://github.com/PX4-NuttX/nuttx/tree/master
 - https://github.com/PX4-NuttX/nuttx/commit/bf88e6d250fffb3f2b9c6dce2825915350d62460

Changes from PX4/NuttX (https://github.com/PX4/NuttX/commit/828d156df7f98746ca2f0eb6f690721bf551cd7d) in current PX4/master (8d3335906a84fa7028f27c990343ab97071d5319)
https://github.com/PX4/NuttX/compare/828d156df7f98746ca2f0eb6f690721bf551cd7d...bf88e6d250fffb3f2b9c6dce2825915350d62460

bf88e6d250 (HEAD, origin/master) stm32f334-disco/src/stm32_smps.c: fix compilation error
61389ad616 libdsp: update some comments
781cd3f65b libdsp: fix typos
f05edf1a5b libdsp: fix nxstyle errors
255ffcf852 libdsp: add support for fixed16 libdsp
f248207717 libdsp/Kconfig: move configuration to menuconfig, add option to include vabc in FOC data
a2afb2daa9 libdsp: add Permanent Magnet Synchronous Motor (PMSM) model
eeab79bd52 libdsp/lib_motor.c: remove reference to some unused data
1e02175ae7 include/dsp.h: add DIR_NONE definition
eadc7ebb1a libdsp/lib_observer.c: optimize and add some comments

Apps:
 - https://github.com/PX4/NuttX-apps/tree/master
 - https://github.com/PX4/NuttX-apps/commit/b9042a36664b1baff90d7bacedf166f1ce3d628a

Changes from PX4/NuttX-apps (https://github.com/PX4/NuttX-apps/commit/9be72aa9c351186d7f7e54aad32a45b7f2ea3ee0) in current PX4/master (8d3335906a84fa7028f27c990343ab97071d5319)
https://github.com/PX4/NuttX-apps/compare/9be72aa9c351186d7f7e54aad32a45b7f2ea3ee0...b9042a36664b1baff90d7bacedf166f1ce3d628a

b9042a36 (HEAD -> master, origin/master) CI: cancel redundant workflows
0f7ee888 neutils/mqttc: Update to version 1.1.5
3638f1c3 lvgldemo: Add support for lcddev
d548803d httpd: expose http_send_headers to be used in CGI handlers
36d4bfa7 mqttc example: provide sane hostname default to avoid crash
a4e170b7 remove examples/dsptest
d3c75083 testing/fstest: Add hash checking of file's name to avoid creating same-name file
6ae35ffc examples: Add an MQTT-C example.
e35ea948 mqtt: Add glue code to download MQTT-C.
52d853e6 system/nxplayer: Fix error: 'outstanding' undeclared